# Generated by Django 3.2.19 on 2023-06-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
